name: "sample-tiktok"
mode: "dev"
port: 2024
start_time: "2023-01-20"
machine_id: 1

JwtAuth:
  AccessSecret: "lxj-whl-zht-tzy"
  # 24小时
  AccessExpire: 86400
  # 7天
  RefreshExpire: 604800
  Issuer: "Four-swordsmen"

FTP:
  ServerAddr: "1.12.58.218:21"
  Name: "test1"
  Pwd: "74563jkas"

Mysql:
  Host: "hymsk.asia"
  Port: "3306"
  User: "tiktok_user"
  Pwd: "tiktok_passwd_2024"
  DBname: "tiktok"
  Max_open_conns: 200
  Max_idle_conns: 50

Video:
  PlayUrlPrefix: "https://static.tiktok.hymsk.asia/videos"
  CoverUrlPrefix: "https://static.tiktok.hymsk.asia/covers"
  PlayStaticPrefix: "/home/tiktok/static/videos"
  CoverStaticPrefix: "/home/tiktok/static/covers"
  ProfilePhotoPrefix: "http://static.tiktok.hymsk.asia/profile_photo.png"
  PageSize : 5



